planner:
  mode: "VisPRM" # "VisRRT" or "VisPRM"
  use_visual_ik: true
  use_visibility_integrity: true

  # Planning Group & Links
  group_name: "manipulator"
  # ee_link_name: "ur_arm_tool0"
  # ee_link_name: "flashlight"
  ee_link_name: "light_beam"

  # # General Settings
  resolution: 0.01
  visibility_threshold: 0.99
  workspace_bounds:
    x_min: -1.0
    x_max: 1.0
    y_min: -1.0
    y_max: 1.0
    z_min: -0.25
    z_max: 1.5

  # Visibility tool Parameters
  visibility_tool_params:
    beam_length: 1.0
    beam_angle: 0.21

  # Post-Processing
  enable_shortcutting: true

  # RRT Specific Parameters
  rrt:
    goal_bias: 0.125
    max_extension: 3.0
    max_iterations: 10000

  # # PRM Specific Parameters
  prm:
    num_neighbors: 10
    num_samples: 50
    # 0 = LINEAR, 1 = BINARY_SEARCH
    edge_validation_method: 1

  visibility_integrity:
    num_samples: 3000
    vi_threshold: 0.8
    k_neighbors: 5
    limit_diameter_factor: 2.0
    face_samples: 10
