planner:
  mode: "VisPRM" # "VisRRT" or "VisPRM"
  use_visual_ik: false
  use_visibility_integrity: true
  time_cap: 60 #seconds

  # Planning Group & Links
  group_name: "manipulator"
  # ee_link_name: "ur_arm_tool0"
  # ee_link_name: "tool0"
  # ee_link_name: "flashlight"
  ee_link_name: "light_beam"

  # # General Settings
  resolution: 0.01
  visibility_threshold: 0.7
  workspace_bounds:
    x_min: -2.0
    x_max: 2.0
    y_min: -2.0
    y_max: 2.0
    z_min: -0.25
    z_max: 2.5

  # Visibility tool Parameters
  visibility_tool_params:
    beam_length: 3.0
    beam_angle: 0.21

  # Post-Processing
  enable_shortcutting: true

  # RRT Specific Parameters
  rrt:
    goal_bias: 0.125
    max_extension: 3.0
    max_iterations: 100000

  # # PRM Specific Parameters
  prm:
    num_neighbors: 7
    num_samples: 50
    max_goals: 10
    # 0 = LINEAR, 1 = BINARY_SEARCH
    edge_validation_method: 1
    max_size: 5000

  visibility_integrity_params:
    num_samples: 1000
    vi_threshold: 0.6
    k_neighbors: 5
    limit_diameter_factor: 2.0
    face_samples: 10
