target_points:
  # - [ 0.8, 0.02, 1.18 ]
  # - [ 0.8, 0.02, 1.12 ]
  # - [0.195, -1.13, 0.79]
  # - [0.195, -1.13, 0.89]
  # - [-0.22, -0.65, 0.855]
  # - [-0.16, -0.65, 0.855]
  # - [-0.22, -0.65, 0.555]
  # - [-0.16, -0.65, 0.555]
  - [0.65, -0.83, 0.84]
  - [0.65, -0.77, 0.84]  